# Generated by Django 3.1.5 on 2021-01-30 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotels',
            old_name='image',
            new_name='hotel_image',
        ),
    ]
